import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe,expect,it,vi } from 'vitest'
import { createLogger } from '@zamam/observability'
import { createApi } from '../services/functions/src/api/api'
import { createFeatureRoutes,DisabledFeatureCommandDispatcher,FEATURE_API_PATHS } from '../services/functions/src/api/feature-routes'
import { InMemoryIdempotencyStore,InMemoryOutbox,InMemoryRateLimiter } from '../services/functions/src/platform/in-memory'
describe('trusted API route coverage',()=>{
  it('registers every literal V1 endpoint used by web clients',()=>{const root=join(process.cwd(),'apps','web','src');const files=['auth/api.ts',...Array.from(requireFeatureClients())];const used=new Set<string>();const endpointPattern=new RegExp("['`](/v1/[A-Za-z0-9_/-]+)['`]",'g');for(const file of files){const source=readFileSync(join(root,file),'utf8');for(const match of source.matchAll(endpointPattern))used.add(match[1]!)}expect([...used].sort()).toEqual([...FEATURE_API_PATHS].sort())})
  it('returns explicit 503 for uncomposed feature backends rather than 404 or unsafe fallback',async()=>{const api=createApi({allowedOrigins:new Set(),logger:createLogger({write:vi.fn()}),idempotencyStore:new InMemoryIdempotencyStore(),outbox:new InMemoryOutbox(),rateLimiter:new InMemoryRateLimiter(),tokenVerifier:{verify:vi.fn().mockResolvedValue({userId:'u1',tokenIssuedAt:1,emailVerified:true})},appCheckVerifier:{verify:vi.fn()},routes:createFeatureRoutes(new DisabledFeatureCommandDispatcher())});const response=await api(new Request('https://local/v1/tasks/query',{method:'POST',headers:{authorization:'Bearer token-value-long','x-firebase-appcheck':'test','x-idempotency-key':'request-key-1','content-type':'application/json'},body:JSON.stringify({organizationId:'org-1'})}));expect(response.status).toBe(503);expect(await response.json()).toMatchObject({error:{code:'SERVICE_UNAVAILABLE'}})})
  it('allows public auth routes through App Check without requiring a user bearer',async()=>{const dispatcher={execute:vi.fn().mockResolvedValue({accepted:true,messageCode:'REQUEST_ACCEPTED'})};const verify=vi.fn();const api=createApi({allowedOrigins:new Set(),logger:createLogger({write:vi.fn()}),idempotencyStore:new InMemoryIdempotencyStore(),outbox:new InMemoryOutbox(),rateLimiter:new InMemoryRateLimiter(),tokenVerifier:{verify},appCheckVerifier:{verify:vi.fn()},routes:createFeatureRoutes(dispatcher)});const response=await api(new Request('https://local/v1/auth/password-reset',{method:'POST',headers:{'x-firebase-appcheck':'test','x-idempotency-key':'public-key-1','content-type':'application/json'},body:JSON.stringify({email:'user@example.test'})}));expect(response.status).toBe(200);expect(verify).not.toHaveBeenCalled();expect(dispatcher.execute).toHaveBeenCalledWith('/v1/auth/password-reset',expect.objectContaining({principal:expect.objectContaining({userId:'public-auth'})}),{email:'user@example.test'})})
})
function requireFeatureClients(){return ['features/organization/client.ts','features/employees/client.ts','features/clients/client.ts','features/projects/client.ts','features/workspaces/client.ts','features/tasks/client.ts','features/workflows/client.ts','features/reviews/client.ts','features/templates/client.ts','features/collaboration/client.ts','features/files/client.ts','features/notifications/client.ts','features/workload/client.ts','features/time/client.ts','features/attendance/client.ts','features/reports/client.ts','features/automations/client.ts','features/ai/client.ts','features/portal/client.ts']}
