import { describe, expect, it, vi } from 'vitest'
import { validateAutomationDefinition } from '@zamam/domain'
import { AutomationRunJob, type AutomationRunStore, type AutomationWorkItem } from '../services/workers/src'
class Store implements AutomationRunStore { begun = new Set<string>(); completed: unknown[] = []; retries: unknown[] = []; dead: unknown[] = []; allow = true; async begin(id:string){ if(this.begun.has(id)) return 'duplicate' as const; this.begun.add(id); return 'created' as const } async complete(id:string,r:readonly Readonly<Record<string,unknown>>[]){this.completed.push([id,r])} async retry(id:string,a:number,c:string){this.retries.push([id,a,c])} async deadLetter(id:string,a:number,c:string){this.dead.push([id,a,c])} async quota(){return this.allow} }
const item = (overrides: Partial<AutomationWorkItem> = {}): AutomationWorkItem => ({ organizationId:'org-1', automationId:'automation-1', automationVersion:1, triggerEventId:'event-1', triggerDepth:0, conditions:[{field:'status',operator:'eq',value:'ready'}], actions:[{type:'task.add_tag',arguments:{tagId:'tag-1'}}], payload:{status:'ready'}, servicePrincipalId:'service-1', scopeType:'team', scopeId:'team-1', attemptCount:0, ...overrides })
describe('automation engine', () => {
  it('rejects arbitrary/high-risk actions and direct loops', () => { expect(() => validateAutomationDefinition({ triggerEvent:'task.tag_added',conditions:[],actions:[{type:'task.add_tag',arguments:{}}] })).toThrow('AUTOMATION_DIRECT_LOOP_DENIED'); expect(() => validateAutomationDefinition({ triggerEvent:'task.created',conditions:[],actions:[{type:'task.delete' as never,arguments:{}}] })).toThrow('AUTOMATION_ACTION_DENIED') })
  it('deduplicates a logical run and uses action idempotency with least-privilege permission', async () => { const store=new Store(); const execute=vi.fn().mockResolvedValue({resourceType:'task',resourceId:'task-1'}); const job=new AutomationRunJob(store,{execute}); await job.run(item()); expect((await job.run(item())).duplicate).toBe(true); expect(execute).toHaveBeenCalledWith(expect.objectContaining({servicePrincipalId:'service-1',permission:'task.update',idempotencyKey:expect.stringContaining('action-0')})) })
  it('bounds loop depth and quotas', async () => { const store=new Store(); const job=new AutomationRunJob(store,{execute:vi.fn()}); await expect(job.run(item({triggerDepth:3}))).rejects.toThrow('AUTOMATION_DEPTH_DENIED'); store.allow=false; await expect(job.run(item())).rejects.toThrow('AUTOMATION_QUOTA_EXCEEDED') })
  it('retries failures then dead-letters at five attempts', async () => { const store=new Store(); const job=new AutomationRunJob(store,{execute:vi.fn().mockRejectedValue(new Error('TARGET_UNAVAILABLE'))}); await job.run(item()); expect(store.retries).toHaveLength(1); const last=new Store(); await new AutomationRunJob(last,{execute:vi.fn().mockRejectedValue(new Error('TARGET_UNAVAILABLE'))}).run(item({attemptCount:4})); expect(last.dead).toHaveLength(1) })
  it('skips unmatched conditions without an action', async () => { const store=new Store(); const execute=vi.fn(); expect((await new AutomationRunJob(store,{execute}).run(item({payload:{status:'draft'}}))).skipped).toBe(true); expect(execute).not.toHaveBeenCalled() })
})
