import { describe,expect,it,vi } from 'vitest'
import type { AuthorizationPrincipal } from '@zamam/authorization'
import type { AtomicStore,AtomicTransaction,StoredDocument } from '@zamam/firestore'
import { PortalService,type PortalDataPort } from '../services/functions/src/portal/service'
class Store implements AtomicStore{records=new Map<string,StoredDocument>();async runTransaction<T>(operation:(transaction:AtomicTransaction)=>Promise<T>){const working=new Map(this.records);const result=await operation({get:async path=>working.get(path)??null,create:(path,data)=>{if(working.has(path))throw new Error('EXISTS');working.set(path,data)},update:(path,data)=>working.set(path,{...working.get(path),...data})});this.records=working;return result}}
const principal=(overrides:Partial<AuthorizationPrincipal>={}):AuthorizationPrincipal=>({userId:'portal-user',authenticated:true,tokenFresh:true,accountStatus:'active',employmentStatus:'not_applicable',organizationId:'org-1',membershipStatus:'active',principalType:'client',clientAccountIds:['client-1'],stepUpSatisfied:true,mfaSatisfied:true,...overrides})
const metadata=(p=principal())=>({organizationId:'org-1',principal:p,correlationId:'correlation-1',idempotencyKey:'idempotency-1',fingerprint:'fingerprint-1'})
const port=(overrides:Partial<PortalDataPort>={}):PortalDataPort=>({contactForUser:vi.fn().mockResolvedValue({id:'contact-1',organizationId:'org-1',clientId:'client-1',portalStatus:'active'}),projectMemberships:vi.fn().mockResolvedValue([{organizationId:'org-1',projectId:'project-1',userId:'portal-user',principalType:'client',access:'viewer',status:'active'}]),projects:vi.fn().mockResolvedValue([{id:'project-1',organizationId:'org-1',clientId:'client-1',clientVisible:true,name:'Public project',code:'P1',status:'active',managerUserId:'secret-manager',departmentId:'secret-dept',financial:{budget:99}}]),projectItems:vi.fn().mockResolvedValue({tasks:[{id:'task-visible',organizationId:'org-1',projectId:'project-1',clientVisible:true,title:'Visible',status:'active',assigneeUserId:'secret-employee'},{id:'task-hidden',organizationId:'org-1',projectId:'project-1',clientVisible:false,title:'Internal',status:'active'}],comments:[{id:'comment-client',organizationId:'org-1',resourceType:'project',resourceId:'project-1',visibility:'client',status:'active',body:'Visible comment'},{id:'comment-internal',organizationId:'org-1',resourceType:'project',resourceId:'project-1',visibility:'internal',status:'active',body:'Internal secret'}],files:[{id:'file-1',organizationId:'org-1',resourceType:'project',resourceId:'project-1',visibility:'client',status:'available',retentionState:'active',displayName:'Delivery.pdf',latestVersionNumber:2,objectKey:'private-key'}],approvals:[{id:'approval-1',organizationId:'org-1',visibility:'client',reviewerUserId:'portal-user',status:'pending',reviewedVersion:3,title:'Approve delivery'}],deliveries:[]}),...overrides})
const gate={require:vi.fn().mockResolvedValue(undefined)}
describe('client portal isolation',()=>{
  it('denies non-client and cross-organization identities before reading projects',async()=>{const data=port();const service=new PortalService(new Store(),gate,data);await expect(service.dashboard(metadata(principal({principalType:'member'})))).rejects.toThrow('PORTAL_IDENTITY_DENIED');await expect(service.dashboard({...metadata(),organizationId:'org-2'})).rejects.toThrow('PORTAL_IDENTITY_DENIED');expect(data.projectMemberships).not.toHaveBeenCalled()})
  it('requires active explicit viewer membership and same client account',async()=>{const service=new PortalService(new Store(),gate,port({projectMemberships:vi.fn().mockResolvedValue([])}));const result=await service.dashboard(metadata());expect(result.projects).toEqual([]);expect(result.pendingApprovals).toEqual([])})
  it('returns a strict projection with no internal fields, comments, task or storage key',async()=>{const service=new PortalService(new Store(),gate,port());const result=await service.project(metadata(),'project-1');const json=JSON.stringify(result);expect(json).toContain('Visible comment');expect(json).not.toContain('Internal secret');expect(json).not.toContain('secret-manager');expect(json).not.toContain('secret-dept');expect(json).not.toContain('secret-employee');expect(json).not.toContain('private-key');expect(json).not.toContain('task-hidden')})
  it('denies project lookup outside explicit memberships without revealing existence',async()=>{const service=new PortalService(new Store(),gate,port());await expect(service.project(metadata(),'project-2')).rejects.toThrow('PORTAL_PROJECT_DENIED')})
  it('creates an audited, tenant-owned request only for a member project',async()=>{const store=new Store();const service=new PortalService(store,gate,port());await service.createRequest(metadata(),{id:'request-1',projectId:'project-1',subject:'New request',description:'Please add this deliverable'});expect(store.records.get('v2Organizations/org-1/client_request/request-1')).toMatchObject({organizationId:'org-1',clientId:'client-1',requestedBy:'portal-user',status:'open'});expect([...store.records.keys()].some(path=>path.includes('/_auditEvents/'))).toBe(true)})
})
